# .github/workflows/ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'env/staging'

permissions:
  packages: write

jobs:
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: secret-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:
            ghcr.io/${{ github.repository }}:${{ github.run_number }}

  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: echo "pytest tests/unit"

      - name: Run Integration Tests
        run: echo "pytest tests/integration"

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy to Minikube
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          DB_HOST: ${{ vars.DB_HOST }}
          APP_IMAGE: ghcr.io/${{ github.repository }}:${{ github.run_number }}

        run: |
          kubectl create ns coffee-app
          kubectl create configmap -n coffee-app coffee-app-config --from-env-file=.env
          kubectl create secret generic -n coffee-app coffee-app-secret --from-literal=POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          kubectl describe -n coffee-app secret coffee-app-secret
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl describe -n coffee-app service coffee-db-service
          sed "s|APP_IMAGE|${APP_IMAGE}|" k8s/fastapi-deployment.yaml | kubectl apply -f -
          kubectl describe -n coffee-app service coffee-app-service

      - name: Verify deployment
        run: |
          kubectl get pods -n coffee-app
          kubectl rollout status deployment/coffee-app-deployment -n coffee-app

      - name: Check service via curl
        run: |
          minikube service list
          minikube service coffee-app-service --url -n coffee-app
          URL=$(minikube service coffee-app-service --url -n coffee-app)
          curl $URL
